const COLORS = {
  brand: {
    primary: "#005128",
    primaryDark: "#003d1e",
    primarySoft: "#e6f0eb",
    accentGreen: "#1B7347",
    accentRed: "#FA0000",
    accentRedSoft: "#FFE5E5",
  },
  semantic: {
    success: "#22C55E",
    successDark: "#16A34A",
    successSoft: "#DCFCE7",
    veg: "#22C55E",
    vegDark: "#15803D",
    vegSoft: "#ECFDF3",
    warning: "#F59E0B",
    error: "#DC2626",
  },
  neutral: {
    textPrimary: "#0F172A",
    textSecondary: "#64748B",
    textMuted: "#94A3B8",
    surface: "#FFFFFF",
    surfaceAlt: "#F8FAFC",
    surfaceMuted: "#F1F5F9",
    border: "#D9E7FF",
    borderSoft: "#E2E8F0",
    black: "#000000",
    white: "#FFFFFF",
  },
};

export const BRAND_THEME = {
  brandName: "Bakala",
  logoReference: {
    fileName: "WhatsApp_Image_2026-04-04_at_11.41.58_AM-removebg-preview.png",
    sourcePath:
      "C:/Users/aditi/Downloads/WhatsApp_Image_2026-04-04_at_11.41.58_AM-removebg-preview.png",
  },
  colors: COLORS,
  tokens: {
    app: {
      pageBackground: "#FFFFFF",
      cardBackground: "#FFFFFF",
      sectionBackground: "#FFFFFF",
      sectionAltBackground: "#F1F5F9",
      primaryText: "#0F172A",
      secondaryText: "#64748B",
      mutedText: "#94A3B8",
      border: "#D9E7FF",
    },
    motion: {
      duration: {
        fast: "180ms",
        normal: "300ms",
        slow: "500ms",
      },
      easing: {
        standard: "cubic-bezier(0.4, 0, 0.2, 1)",
        decelerate: "cubic-bezier(0, 0, 0.2, 1)",
        accelerate: "cubic-bezier(0.4, 0, 1, 1)",
      },
      distance: {
        revealY: "12px",
        floatY: "16px",
        textY: "10px",
      },
    },
    header: {
      defaultBackground: "transparent",
      scrolledBackground: "#FFFFFF",
      searchBackground: "#FFFFFF",
      searchIcon: COLORS.brand.primary,
    },
    searchOverlay: {
      headerSurface: "bg-white dark:bg-[#1a1a1a]",
      headerBorder: "border-slate-200 dark:border-slate-800",
    },
    navigation: {
      surface: "bg-white dark:bg-[#1a1a1a]",
      border: "border-[#D9E7FF] dark:border-slate-800",
      subtleBorder: "border-slate-200 dark:border-slate-800",
      searchSurface: "bg-white dark:bg-[#1f1f1f] border border-slate-200 dark:border-slate-700",
      searchFocus: `focus-within:ring-2 focus-within:ring-[${COLORS.brand.primary}] focus-within:border-[${COLORS.brand.primary}]/20`,
      iconButtonHover: "hover:bg-slate-100 dark:hover:bg-slate-800",
      iconButtonSurface: "bg-white dark:bg-[#1f1f1f] border border-slate-200 dark:border-slate-700",
      icon: `text-[${COLORS.brand.primary}] dark:text-green-300`,
      badgeRing: "ring-white dark:ring-[#1a1a1a] bg-red-500 text-white",
      activeText: `text-[${COLORS.brand.primary}] dark:text-[#33875f]`,
      inactiveText: `text-gray-600 dark:text-gray-400 hover:text-[${COLORS.brand.primary}] dark:hover:text-[#33875f]`,
      indicator: `bg-[${COLORS.brand.primary}] dark:bg-[#33875f]`,
      divider: "bg-slate-200 dark:bg-slate-700",
    },
    button: {
      primaryBackground: COLORS.brand.primary,
      primaryHover: COLORS.brand.primaryDark,
      primaryText: "#FFFFFF",
      accentBackground: COLORS.brand.primaryDark,
      accentHover: "#002d16",
      accentText: "#FFFFFF",
    },
    footer: {
      background: "#0F172A",
      surfaceText: "#E2E8F0",
      mutedText: "#94A3B8",
      sectionHeading: COLORS.brand.accentGreen,
      brandGradient: `linear-gradient(135deg, ${COLORS.brand.accentGreen} 0%, ${COLORS.brand.primary} 100%)`,
      divider: "#334155",
    },
    location: {
      icon: COLORS.brand.primary,
      iconSoft: COLORS.brand.primarySoft,
      promptOverlay: "rgba(15, 23, 42, 0.52)",
      buttonBorder: "#D9E7FF",
      addressActionBackground: COLORS.brand.primarySoft,
      addressActionText: COLORS.brand.primary,
      liveLocationBlue: COLORS.brand.primary,
    },
    productDetail: {
      pageBackground: "bg-white dark:bg-[#0a0a0a]",
      primaryBadge: `bg-[${COLORS.brand.primary}] text-white`,
      priceText: `text-[${COLORS.brand.primary}]`,
      breadcrumbHover: `hover:text-[${COLORS.brand.primary}]`,
      quantityBorder: `border-[${COLORS.brand.primary}]`,
      quantityHover: `hover:bg-[${COLORS.brand.primarySoft}]`,
      primaryButton: `bg-[${COLORS.brand.primary}] hover:bg-[${COLORS.brand.primaryDark}] text-white`,
      categoryBadge: `bg-[${COLORS.brand.primarySoft}] text-[${COLORS.brand.primary}] border-[#D9E7FF]`,
    },
    notifications: {
      headerIcon: COLORS.brand.primary,
      countBadge: COLORS.brand.primary,
      unreadDot: COLORS.brand.primary,
      unreadBackground: "bg-green-50/70 dark:bg-green-950/20 border-green-200 dark:border-green-900/50",
      readBackground: "bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700",
      offerIcon: `text-[${COLORS.brand.primary}]`,
      broadcastIcon: `text-[${COLORS.brand.primary}]`,
    },
    wallet: {
      pageBackground: "bg-white dark:bg-[#0a0a0a]",
      headerSurface: "bg-white dark:bg-[#1a1a1a]",
      brandGradient: `linear-gradient(145deg, ${COLORS.brand.primary}, ${COLORS.brand.primaryDark})`,
      brandShadow: "rgba(0, 81, 40, 0.28)",
      refundText: `text-[${COLORS.brand.primary}] dark:text-green-400`,
      filterActive:
        `bg-white dark:bg-[#1a1a1a] border-2 border-[${COLORS.brand.primary}] dark:border-green-400 text-[${COLORS.brand.primary}] dark:text-green-300 shadow-sm`,
      addMoneyButton:
        `bg-[${COLORS.brand.primary}] hover:bg-[${COLORS.brand.primaryDark}] text-white`,
    },
    cart: {
      pageBackground: "bg-white dark:bg-[#0a0a0a]",
      primaryText: COLORS.brand.primary,
      primarySurface: COLORS.brand.primarySoft,
      primaryBorder: COLORS.brand.primary,
      primaryButton: `bg-[${COLORS.brand.primary}] hover:bg-[${COLORS.brand.primaryDark}] text-white`,
      primaryButtonAlt: `bg-white border border-[${COLORS.brand.primary}] text-[${COLORS.brand.primary}] hover:bg-green-50`,
      pillSurface: "bg-green-50 text-[#005128] border border-green-100",
      paymentSelected:
        `border-[${COLORS.brand.primary}] bg-[${COLORS.brand.primary}] shadow-lg shadow-green-500/30`,
      paymentHover: "hover:border-green-200 dark:hover:border-green-900/30",
      progressGradient: `linear-gradient(90deg, ${COLORS.brand.primary}, ${COLORS.brand.primaryDark})`,
      successShadow: "shadow-green-200/70 dark:shadow-green-950/40",
    },
    orders: {
      primaryText: COLORS.brand.primary,
      primaryButton: `bg-[${COLORS.brand.primary}] hover:bg-[${COLORS.brand.primaryDark}] text-white`,
      primaryButtonAlt: `bg-white border border-[${COLORS.brand.primary}] text-[${COLORS.brand.primary}] hover:bg-green-50`,
      primaryGradient: `linear-gradient(135deg, ${COLORS.brand.primary} 0%, ${COLORS.brand.primaryDark} 100%)`,
      softSurface: `bg-green-50 border-green-100 text-[${COLORS.brand.primary}]`,
      focusRing: COLORS.brand.primary,
    },
    profile: {
      pageBackground: "bg-white dark:bg-[#0a0a0a]",
      sectionAccent: COLORS.brand.primary,
      accentBar: `bg-[${COLORS.brand.primary}]`,
      avatarBackground: COLORS.brand.primary,
      avatarSurface: `bg-[${COLORS.brand.primary}]`,
      avatarEditButton: `bg-[${COLORS.brand.primary}] hover:bg-[${COLORS.brand.primaryDark}] text-white`,
      fieldFocus: COLORS.brand.primary,
      surface: "bg-white dark:bg-[#1a1a1a]",
      surfaceAlt: "bg-slate-50 dark:bg-slate-800/60",
      border: "border-gray-200 dark:border-gray-800",
      iconSurface: "bg-slate-100 dark:bg-slate-800",
      iconText: "text-slate-700 dark:text-slate-300",
      activeTab: `border-[${COLORS.brand.primary}] text-[${COLORS.brand.primary}]`,
      primaryButton: `bg-[${COLORS.brand.primary}] hover:bg-[${COLORS.brand.primaryDark}] text-white`,
      primaryButtonSoft: `bg-green-50 text-[${COLORS.brand.primary}] border border-green-100 hover:bg-green-100`,
      secondaryButton: "bg-white border border-[#D9E7FF] text-slate-700 hover:bg-slate-50",
      highlightSurface: "bg-green-50 dark:bg-green-950/30 border-green-100 dark:border-green-900/50",
      warningSurface: "bg-amber-50 border-amber-200 text-amber-800",
      destructiveButton: "#FA0000",
      linkText: `text-[${COLORS.brand.primary}]`,
      legalLinkHover: `group-hover:text-[${COLORS.brand.primary}] dark:group-hover:text-green-300`,
    },
    status: {
      vegBackground: "#ECFDF3",
      vegText: "#15803D",
      vegAccent: "#22C55E",
      successBackground: "#DCFCE7",
      successText: "#16A34A",
      dangerBackground: "#FEF2F2",
      dangerText: "#DC2626",
    },
    homepage: {
      shared: {
        accentText: `text-[${COLORS.brand.primary}]`,
        accentSoft: `bg-[${COLORS.brand.primarySoft}] text-[${COLORS.brand.primary}] hover:bg-green-100 dark:bg-green-950/30 dark:text-green-300`,
        accentBorder: `group-hover:border-[${COLORS.brand.primary}]/20`,
      },
      header: {
        iconAccent: COLORS.brand.primary,
        cartBadgeBackground: COLORS.brand.primaryDark,
        searchRailGradient: `linear-gradient(180deg, ${COLORS.brand.primary} 0%, ${COLORS.brand.primaryDark} 100%)`,
        foodPatternTint: COLORS.brand.primary,
      },
      desktopNav: {
        activeText: `text-[${COLORS.brand.primary}] dark:text-[#33875f]`,
        inactiveText: `text-gray-600 dark:text-gray-400 hover:text-[${COLORS.brand.primary}] dark:hover:text-[#33875f]`,
        indicator: `bg-[${COLORS.brand.primary}] dark:bg-[#33875f]`,
        searchFocus: `focus-within:ring-2 focus-within:ring-[${COLORS.brand.primary}] focus-within:bg-white dark:focus-within:bg-[#1a1a1a] border border-transparent focus-within:border-[${COLORS.brand.primary}]/20`,
      },
      home: {
        chipHoverBorder: `group-hover:border-[${COLORS.brand.primary}]`,
        chipMoreBackground: "bg-green-50 dark:bg-green-950/40",
        chipMoreBorder: `border-green-100 group-hover:border-[${COLORS.brand.primary}]`,
        chipMoreIcon: `text-[${COLORS.brand.primary}]`,
        exploreOverlayPalette: [
          "from-emerald-500 to-green-600",
          "from-teal-500 to-cyan-600",
          "from-lime-500 to-emerald-600",
          "from-green-500 to-teal-600",
        ],
        promoBadgeBackground: COLORS.brand.primary,
        promoBadgeText: COLORS.brand.primary,
        promoAccentText: `text-[${COLORS.brand.primary}]`,
        promoAccentFill: `fill-[${COLORS.brand.primary}]`,
        exploreHoverBorder: `group-hover:border-[${COLORS.brand.primary}]/30`,
        exploreHoverGlow: `group-hover:shadow-[inset_0_0_0_1px_rgba(0,81,40,0.22)]`,
        restaurantCard: {
          bookmarkActive: `bg-[${COLORS.brand.primary}] text-white`,
          bookmarkIdle: `bg-white/90 backdrop-blur-sm text-gray-800 hover:bg-white hover:text-[${COLORS.brand.primary}]`,
          nameHover: `group-hover:text-[${COLORS.brand.primary}]`,
          closingBadge: `bg-green-50 text-[${COLORS.brand.primary}] border border-green-100 dark:bg-green-950/40 dark:text-green-200 dark:border-green-900/60`,
          metaIcon: `text-[${COLORS.brand.primary}] dark:text-green-300`,
          featuredDishBadge: "bg-black/60 backdrop-blur-md text-white border border-white/10",
        },
        promoCards: {
          offersGradient: `linear-gradient(145deg, ${COLORS.brand.primary}, ${COLORS.brand.primaryDark})`,
          offersShadow: "rgba(0, 81, 40, 0.30)",
          under250Gradient: `linear-gradient(145deg, ${COLORS.brand.primary}, ${COLORS.brand.primaryDark})`,
          under250Shadow: "rgba(0, 81, 40, 0.30)",
          combosGradient: `linear-gradient(145deg, ${COLORS.brand.primaryDark}, #002d16)`,
          combosShadow: "rgba(0, 61, 30, 0.32)",
        },
      },
      filters: {
        clearAllText: `text-[${COLORS.brand.primary}]`,
        sidebarActive: `bg-white dark:bg-[#1a1a1a] text-[${COLORS.brand.primary}]`,
        sidebarIndicator: `bg-[${COLORS.brand.primary}]`,
        activeCard: `border-[${COLORS.brand.primary}] bg-[${COLORS.brand.primarySoft}] dark:bg-green-950/30`,
        inactiveCard: `border-gray-200 dark:border-gray-800 hover:border-[${COLORS.brand.primary}]`,
        activeText: `text-[${COLORS.brand.primary}]`,
        activeIcon: `text-[${COLORS.brand.primary}]`,
        activeIconFill: `text-[${COLORS.brand.primary}] fill-[${COLORS.brand.primary}]`,
        primaryButton: `bg-[${COLORS.brand.primary}] text-white hover:bg-[${COLORS.brand.primaryDark}]`,
      },
    },
  },
  gradients: {
    primary: `linear-gradient(135deg, ${COLORS.brand.primary} 0%, ${COLORS.brand.primaryDark} 100%)`,
    hero: "linear-gradient(180deg, #FFFFFF 0%, #FFFFFF 100%)",
    accent: `linear-gradient(135deg, ${COLORS.brand.accentGreen} 0%, ${COLORS.brand.primary} 100%)`,
  },
};

export default BRAND_THEME;
